pipeline:
  tests:
    image: redmineup/redmine_agile
    pull: true
    commands:
      - service postgresql start && service mysql start && sleep 5
      - export PATH=~/.rbenv/shims:$PATH
      - export CODEPATH=`pwd`
      - /root/run_for.sh redmine_agile+${LICENSE} ${RUBY_VER} ${DB} ${REDMINE} ${PLUGINS}
matrix:
  include:
    - RUBY_VER: ruby-2.2.6
      LICENSE: pro
      DB: mysql
      REDMINE: redmine-3.4
    - RUBY_VER: ruby-2.2.6
      LICENSE: light
      DB: mysql
      REDMINE: redmine-3.4
    - RUBY_VER: ruby-2.2.6
      LICENSE: pro
      DB: pg
      REDMINE: redmine-3.4
    - RUBY_VER: ruby-2.2.6
      LICENSE: light
      DB: pg
      REDMINE: redmine-3.4
    - RUBY_VER: ruby-2.2.6
      LICENSE: pro
      DB: mysql
      REDMINE: redmine-3.0
    - RUBY_VER: ruby-2.4.1
      DB: mysql
      LICENSE: light
      REDMINE: redmine-4.0
    - RUBY_VER: ruby-2.4.1
      DB: pg
      LICENSE: pro
      REDMINE: redmine-4.0
    - RUBY_VER: ruby-2.4.1
      DB: mysql
      LICENSE: pro
      REDMINE: redmine-4.0
      PLUGINS: redmine_checklists+pro
      PLUGIN: redmine_agile
      COVERAGE_EXPORT: 1
    - RUBY_VER: ruby-1.9.3
      DB: pg
      LICENSE: pro
      REDMINE: redmine-2.6
    - RUBY_VER: ruby-1.9.3
      DB: pg
      LICENSE: pro
      REDMINE: redmine-3.3
    - RUBY_VER: ruby-1.9.3
      DB: mysql
      LICENSE: pro
      REDMINE: redmine-3.3
    - RUBY_VER: ruby-1.9.3
      DB: pg
      LICENSE: light
      REDMINE: redmine-3.3
    - RUBY_VER: ruby-2.4.1
      DB: mysql
      LICENSE: pro
      REDMINE: redmine-trunk
    - RUBY_VER: ruby-2.4.1
      DB: mysql
      LICENSE: light
      REDMINE: redmine-trunk
    - RUBY_VER: ruby-2.4.1
      DB: pg
      LICENSE: pro
      REDMINE: redmine-trunk
    - RUBY_VER: ruby-2.2.6
      DB: mysql
      LICENSE: pro
      REDMINE: redmine-trunk